### PR TITLE
Remove __class__ on contact attach_attributes_to

### PR DESCRIPTION
**Pull request by ecomba**
When calling list_contacts function from the contacts service returns a list of all of the same contacts.

For example (I changed my contact id to 12345 for the example):

>>> contact_list = client.contacts.list_contacts(account_id)
>>> for contact in contact_list.data:
...     print(contact.id)
...
12345
12345
12345
>>>
The contact struct gets overwritten when it is created.

### CODE REVIEW

**Comment by ecomba** [comment]
@colbyprior Could you add a. test to "prove" the fix does indeed fix the problem?

If you add these two lines (marked with two **) in `test/services/contacts_test.py` it should do the trick:

```python
def test_list_contacts(self):
         responses.add(DNSimpleMockResponse(method=responses.GET,
                                            path='/1010/contacts',
                                            fixture_name='listContacts/success'))
         contacts = self.contacts.list_contacts(1010).data

         self.assertEqual(2, len(contacts))
         self.assertIsInstance(contacts[0], Contact)
         **self.assertEqual(1, contacts[0].id)**
         **self.assertEqual(2, contacts[1].id)**
```

**Comment by colbyprior** [comment]
Thanks for that. I added the tests and with my change it passes.
There same function is called in a few different classes:
- webhook
- template_record
- template
- pagination

I tested the first 3 and they can all be fixed in the same way. There would only ever be one pagination object so I don't think it could be affected but it could be changed to keep everything the same.

Let me know if you would like me to make these changes and add tests or if I should keep this PR just to contacts. I created a branch with the extra changes here:
https://github.com/colbyprior/dnsimple-python/tree/fix_attach_attributes_class_call

**Comment by ecomba** [comment]
> Thanks for that. I added the tests and with my change it passes. There same function is called in a few different classes:
> 
> * webhook
> * template_record
> * template
> * pagination
> 
> I tested the first 3 and they can all be fixed in the same way. There would only ever be one pagination object so I don't think it could be affected but it could be changed to keep everything the same.
> 
> Let me know if you would like me to make these changes and add tests or if I should keep this PR just to contacts. I created a branch with the extra changes here: https://github.com/colbyprior/dnsimple-python/tree/fix_attach_attributes_class_call

Thank you so much for the update! I think the best thing is to create another PR. You don't need to do one for each, just call it something that shows the intention of the PR for the remaining objects and it'll be fine. Also don't forget to add tests that prove this is actually working!

🙏🏼

**Comment by colbyprior** [comment]
Moved to PR https://github.com/dnsimple/dnsimple-python/pull/256

**Comment by ecomba** [comment]
Closing this as it was moved to another PR

**Pull request closed without merging**
